behaviors:
  CarDriverAI:
    trainer_type: ppo
    hyperparameters:
      batch_size: 256
      buffer_size: 10240
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
    checkpoint_interval: 500000
    keep_checkpoints: 50
    max_steps: 10000000
    time_horizon: 64
    summary_freq: 50000

environment_parameters: 
  track_length:
    curriculum:
      - name: "1 block"
        completion_criteria:
          measure: reward
          behavior: CarDriverAI
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value: 1
      - name: "2 blocks"
        completion_criteria:
          measure: reward
          behavior: CarDriverAI
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 2
      - name: "4 blocks"
        completion_criteria:
          measure: reward
          behavior: CarDriverAI
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.5
        value: 4
      - name: "8 blocks"
        value: 8
  max_steps:
    curriculum:
      - name: "1 block"
        completion_criteria:
          measure: reward
          behavior: CarDriverAI
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value: 1500
      - name: "2 blocks"
        completion_criteria:
          measure: reward
          behavior: CarDriverAI
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1.5
        value: 2000
      - name: "4 blocks"
        completion_criteria:
          measure: reward
          behavior: CarDriverAI
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 2.5
        value: 2500
      - name: "8 blocks"
        value: 3000
  
    
